#!/bin/bash

# The user that should run your minecraft worlds.
USER=minecraft

# The root directory of the EMSM.
# This directory contains the *emsm* directory.
LOCATION=/home/$USER

# Change nothing below this line.
# -----------------------------------------------
eval "su -c 'cd $LOCATION && python3 emsm/application.py $@' $USER"
