#!/bin/bash

# The user that should run your minecraft worlds.
USER=minecraft

# The root directory of the EMSM.
# This directory contains the *emsm* directory.
LOCATION=/home/$USER

# Change nothing below this line.
# -----------------------------------------------
eval "su --shell=/bin/bash -c 'python3 $LOCATION/emsm/application.py $@' $USER"
