#!/bin/bash
### BEGIN INIT INFO
# Provides:          EMSM - extendable minecraft server manager
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops your minecraft worlds.
### END INIT INFO

EMSM=`which minecraft`
PLUGIN=initd

test -x $EMSM || exit 0
source /lib/lsb/init-functions

case "$1" in
   start)
      log_daemon_msg "Starting minecraft server" ""
      $EMSM $PLUGIN --start
      log_end_msg $?
      ;;
   stop)
      log_daemon_msg "Stopping minecraft server" ""
      $EMSM $PLUGIN --stop
      log_end_msg $?
      ;;
   restart)
      $0 stop
      $0 start
      ;;
   *)
      echo "Usage: $0 {start|stop|restart}" >&2
      exit 1
      ;;
esac
